"""Tests for System 2 Shared Infrastructure components S1 and S2.

Uses a small fixture dataset generated by System 1 in a tempdir so the tests
are fast and self-contained.
"""

from __future__ import annotations

import json
from pathlib import Path

import networkx as nx
import joblib
import numpy as np
import pandas as pd
import pytest

from src.system1_generator import g1_account_builder, g2_normal_generator, g3_scenario_injector, g4_splitter
from src.system1_generator.common import CONFIG_PATH, GeneratorConfig
from src.system2_detection.shared import s1_feature_engineering, s2_multigraph_builder
from src.system2_detection.shared.schemas import FEATURE_COLUMNS


@pytest.fixture(scope="session")
def shared_fixture(tmp_path_factory):
    """Generate a small dataset, then run S1 + S2 against it."""
    out_dir = tmp_path_factory.mktemp("shared-fixture")
    cfg = GeneratorConfig.from_file(CONFIG_PATH).override(
        num_accounts=400,
        num_historical_transactions=8_000,
        num_stream_transactions=2_000,
    )
    ctx = g1_account_builder.build_accounts(cfg)
    g1_account_builder.save_accounts(ctx)
    normal_df = g2_normal_generator.generate_normal(cfg, ctx)
    combined, suspicious, gt = g3_scenario_injector.inject_scenarios(cfg, ctx, normal_df)
    hist_df, stream_df = g4_splitter.split_and_export(combined, gt, out_dir=out_dir)

    historical_csv = out_dir / "historical_transactions.csv"
    artifact_dir = out_dir / "artifacts"

    # S1
    features, scaler = s1_feature_engineering.build_features(historical_csv=historical_csv)
    s1_feature_engineering.save_features(features, scaler, out_dir=artifact_dir)

    # S2 — uses accounts.parquet from data/internal which was written above
    G, node_idx, edge_idx = s2_multigraph_builder.build_multigraph(
        historical_csv=historical_csv, accounts_df=ctx.accounts
    )
    s2_multigraph_builder.save_artifacts(G, node_idx, edge_idx, out_dir=artifact_dir)

    return {
        "hist_df": hist_df,
        "features": features,
        "scaler": scaler,
        "graph": G,
        "node_index": node_idx,
        "edge_index": edge_idx,
        "artifact_dir": artifact_dir,
    }


# --------------------------------------------------------------------------- #
# S1 — feature engineering
# --------------------------------------------------------------------------- #


def test_s1_row_count_matches_historical(shared_fixture):
    features = shared_fixture["features"]
    hist_df = shared_fixture["hist_df"]
    assert len(features) == len(hist_df)


def test_s1_has_45_feature_columns(shared_fixture):
    features = shared_fixture["features"]
    # 2 key columns + 45 feature columns = 47 total
    assert features.shape[1] == 47, f"expected 47 cols (2 keys + 45 features), got {features.shape[1]}"
    for col in FEATURE_COLUMNS:
        assert col in features.columns, f"missing feature column: {col}"


def test_s1_transaction_ids_unique_and_complete(shared_fixture):
    features = shared_fixture["features"]
    hist_df = shared_fixture["hist_df"]
    assert features["transaction_id"].is_unique
    assert set(features["transaction_id"]) == set(hist_df["transaction_id"])


def test_s1_scaler_artifact_loadable(shared_fixture):
    artifact_dir = shared_fixture["artifact_dir"]
    scaler_path = artifact_dir / "feature_scaler.pkl"
    parquet_path = artifact_dir / "behavioral_features.parquet"
    assert scaler_path.exists()
    assert parquet_path.exists()
    loaded = joblib.load(scaler_path)
    assert loaded.n_features_in_ == 45


def test_s1_features_are_finite(shared_fixture):
    features = shared_fixture["features"]
    matrix = features[list(FEATURE_COLUMNS)].astype(float).to_numpy()
    assert np.isfinite(matrix).all(), "non-finite values in feature matrix"


def test_s1_velocity_features_monotone_in_window_size(shared_fixture):
    """tx_velocity_1h <= tx_velocity_6h <= tx_velocity_24h <= tx_velocity_7d per row."""
    f = shared_fixture["features"]
    assert (f["tx_velocity_1h"] <= f["tx_velocity_6h"] + 1e-6).all()
    assert (f["tx_velocity_6h"] <= f["tx_velocity_24h"] + 1e-6).all()
    assert (f["tx_velocity_24h"] <= f["tx_velocity_7d"] + 1e-6).all()


def test_s1_flag_features_are_boolean(shared_fixture):
    f = shared_fixture["features"]
    for col in (
        "round_amount_flag",
        "sub_threshold_flag",
        "impossible_travel_flag",
        "high_risk_country_flag",
        "new_device_flag",
    ):
        assert f[col].dtype == bool, f"{col} dtype {f[col].dtype} (expected bool)"


def test_s1_amount_zscore_centered(shared_fixture):
    """For accounts with stable activity, amount_zscore should average near 0."""
    f = shared_fixture["features"]
    median_z = f["amount_zscore"].median()
    assert abs(median_z) < 1.0, f"amount_zscore median {median_z:.3f} is far from 0"


# --------------------------------------------------------------------------- #
# S2 — multigraph builder
# --------------------------------------------------------------------------- #


def test_s2_graph_is_multidigraph(shared_fixture):
    G = shared_fixture["graph"]
    assert isinstance(G, nx.MultiDiGraph)


def test_s2_edge_count_matches_transactions(shared_fixture):
    G = shared_fixture["graph"]
    hist_df = shared_fixture["hist_df"]
    assert G.number_of_edges() == len(hist_df)


def test_s2_multi_edges_preserved(shared_fixture):
    """For any pair (u,v) that appears multiple times in the data, the
    multigraph must have an edge per occurrence."""
    hist_df = shared_fixture["hist_df"]
    G = shared_fixture["graph"]
    # Find a pair with multiple transactions
    pair_counts = hist_df.groupby(["sender_account", "receiver_account"]).size()
    multi_pairs = pair_counts[pair_counts >= 2]
    assert not multi_pairs.empty, "fixture has no multi-edge pair to test"
    u, v = multi_pairs.index[0]
    expected = int(multi_pairs.iloc[0])
    assert G.number_of_edges(u, v) == expected, (
        f"({u},{v}) expected {expected} edges, got {G.number_of_edges(u, v)}"
    )


def test_s2_node_index_covers_all_accounts(shared_fixture):
    G = shared_fixture["graph"]
    node_index = shared_fixture["node_index"]
    assert set(node_index.keys()) == set(G.nodes())
    assert len(set(node_index.values())) == len(node_index), "node indices not unique"


def test_s2_edge_index_round_trip(shared_fixture):
    G = shared_fixture["graph"]
    edge_index = shared_fixture["edge_index"]
    hist_df = shared_fixture["hist_df"]
    assert set(edge_index.keys()) == set(hist_df["transaction_id"])
    # Spot check: every (u, v, key) tuple corresponds to a real edge in G
    sample = list(edge_index.items())[:200]
    for tx_id, triple in sample:
        u, v, key = triple
        assert G.has_edge(u, v, key=key), f"missing edge {u}->{v} key={key}"


def test_s2_node_attrs_populated_for_real_accounts(shared_fixture):
    G = shared_fixture["graph"]
    real_nodes = [n for n in G.nodes() if not str(n).startswith("EXT-")]
    assert real_nodes, "no real-account nodes found"
    # Check first 10 real nodes have non-null bank
    for n in real_nodes[:10]:
        attrs = G.nodes[n]
        assert attrs.get("bank") not in (None, ""), f"node {n} has no bank attr"


def test_s2_artifacts_persisted(shared_fixture):
    artifact_dir = shared_fixture["artifact_dir"]
    assert (artifact_dir / "transaction_multigraph.pkl").exists()
    assert (artifact_dir / "node_index.json").exists()
    assert (artifact_dir / "edge_index.json").exists()
    # node_index.json round-trip
    with open(artifact_dir / "node_index.json", "r", encoding="utf-8") as fh:
        ni = json.load(fh)
    assert ni == shared_fixture["node_index"]
